## Settings
title: multipli.city
owner: "S⧊CREDdata"
url: "https://multipli.city"
baseurl: ""
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "andrew@multipli.city"
github: "sacreddata"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "uninstall your DAW"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "▲⟁◮◬▷▷△◁⧍⧋⧊⨹∧∨⨺⧌⛛◀▶▵⨻⨻⨻"
cdn: "sonicmultiplicities.audio/feed"
podcast:
  title: "▲ Presents: Sonic Multiplicities"
  description: "The official podcast feed for works of Sonic Multiplicities performed by ▲. Each episode presents a complete, unmodified Sonic Multiplicities session, heard here exactly as it was performed at The Cathedral, ▲'s Brooklyn, NY headquarters. Join us for an intimate and intense journey through the roaring musical psyches of some of NYC's finest free improvisers! Highly recommended for fans of electroacoustic music, free and avant-garde jazz, noise music, the violin and the SuperCollider programming language."
  url: /podcast.xml # podcast xml url
  author: "Andrew Grathwohl"
  email: "andrew@multipli.city"
  logo: "https://sonicmultiplicities.audio/triangle.jpg"
  language: "<![CDATA[ en ]]>"
  category: "Arts"
  subcategory: "Performing Arts"
  type: "episodic"
  explicit: false
  complete: "no"
  block: "no"
